import turtle
import time
turtle.hideturtle()
turtle.speed(0)
turtle.up()
turtle.circle(250, 270)
turtle.down()
turtle.begin_fill()
turtle.fillcolor('limegreen')
turtle.circle(-200, 180)
turtle.left(90)
turtle.fd(50)
turtle.right(90)
turtle.begin_fill()
turtle.fillcolor('red')
turtle.circle(200, 180)
turtle.left(90)
turtle.fd(400)
turtle.end_fill
turtle.up()
turtle.goto(-130, 230)
turtle.down()
turtle.begin_fill()
turtle.fillcolor('black')
turtle.circle(25)
turtle.end_fill()
turtle.up()
turtle.goto(-130, 220)
turtle.down()
turtle.begin_fill()
turtle.fillcolor('white')
turtle.circle(15)
turtle.end_fill()
turtle.up()
turtle.goto(130, 230)
turtle.down()
turtle.begin_fill()
turtle.fillcolor('black')
turtle.circle(25)
turtle.end_fill()
turtle.up()
turtle.goto(125, 220)
turtle.down()
turtle.begin_fill()
turtle.fillcolor('white')
turtle.circle(15)
turtle.end_fill()
turtle.up()
turtle.pensize(10)
turtle.goto(15, 100)
turtle.circle(15, 270)
turtle.down()
turtle.circle(15, -180)
turtle.up()
turtle.setpos(25, -25)
turtle.down()
turtle.write('Happy Yalda :)',font = ('Verdana', 12, 'bold'))
time.sleep(25)
turtle.done